services:
  postgres:
    image: postgres:16
    network_mode: host
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: remora_local

  redis:
    image: redis:7
    network_mode: host
    restart: always

  api:
    image: myapi:amd64
    network_mode: host
    restart: always
    environment:
      ENV: local
      # HTTP
      APP_CONFIG_HTTP_ADDR: "0.0.0.0:8080"
      APP_CONFIG_HTTP_CORS_ENABLE: "true"
      # PostgreSQL
      APP_CONFIG_POSTGRESQL_HOST: "127.0.0.1"
      APP_CONFIG_POSTGRESQL_PORT: "5432"
      APP_CONFIG_POSTGRESQL_USER: postgres
      APP_CONFIG_POSTGRESQL_PASSWORD: postgres
      APP_CONFIG_POSTGRESQL_DATABASE: remora_local
      # Redis
      APP_CONFIG_REDIS_HOST: "127.0.0.1"
      APP_CONFIG_REDIS_PORT: "6379"
